//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntrenmanTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class AntrenmanBolge
    {
        public int Id { get; set; }
        public int AntrenmanTuruId { get; set; }
        public int Bolge { get; set; }
        public bool BasariliMi { get; set; }
        public Nullable<int> SporcuId { get; set; }
    }
}
