//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntrenmanTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class AntrenmanTurleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AntrenmanTurleri()
        {
            this.Antrenmanlar = new HashSet<Antrenmanlar>();
        }
    
        public int Id { get; set; }
        public int TopKonumId { get; set; }
        public int TopGelisSekliId { get; set; }
        public int VurusBicimiId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Antrenmanlar> Antrenmanlar { get; set; }
        public virtual TopGelisSekilleri TopGelisSekilleri { get; set; }
        public virtual TopKonumlari TopKonumlari { get; set; }
        public virtual VurusBicimleri VurusBicimleri { get; set; }
    }
}
