//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntrenmanTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Antrenmanlar
    {
        public int Id { get; set; }
        public int SporcuId { get; set; }
        public Nullable<int> AntrenamTuruId { get; set; }
        public int AtisSayisi { get; set; }
        public int BasariliAtis { get; set; }
        public System.DateTime Tarih { get; set; }
        public int AntrenmanSayisi { get; set; }
        public Nullable<int> AntrenmanSuresi { get; set; }
        public Nullable<int> KAntrenmanTuruId { get; set; }
    
        public virtual AntrenmanTurleri AntrenmanTurleri { get; set; }
        public virtual KaleciAntrenmanTurleri KaleciAntrenmanTurleri { get; set; }
        public virtual Sporcular Sporcular { get; set; }
    }
}
