//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntrenmanTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class KayitSablonu
    {
        public int ID { get; set; }
        public Nullable<int> TK { get; set; }
        public Nullable<int> TGS { get; set; }
        public Nullable<int> VB { get; set; }
        public Nullable<int> VK1 { get; set; }
        public Nullable<int> VK2 { get; set; }
        public Nullable<int> VK3 { get; set; }
        public Nullable<int> VK4 { get; set; }
        public Nullable<int> VK5 { get; set; }
        public Nullable<int> VK6 { get; set; }
        public Nullable<int> VK7 { get; set; }
        public Nullable<int> VK8 { get; set; }
        public Nullable<int> VK9 { get; set; }
        public Nullable<int> VK10 { get; set; }
    
        public virtual TopGelisSekilleri TopGelisSekilleri { get; set; }
        public virtual TopKonumlari TopKonumlari { get; set; }
        public virtual VurusBicimleri VurusBicimleri { get; set; }
    }
}
