//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntrenmanTakip
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbAntrenmanTakipEntities : DbContext
    {
        public DbAntrenmanTakipEntities()
            : base("name=DbAntrenmanTakipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<Antrenmanlar> Antrenmanlar { get; set; }
        public virtual DbSet<AntrenmanTurleri> AntrenmanTurleri { get; set; }
        public virtual DbSet<Diller> Diller { get; set; }
        public virtual DbSet<KaleciAntrenmanTurleri> KaleciAntrenmanTurleri { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<KullaniciSporcular> KullaniciSporcular { get; set; }
        public virtual DbSet<Mevkiler> Mevkiler { get; set; }
        public virtual DbSet<Resimler> Resimler { get; set; }
        public virtual DbSet<Sporcular> Sporcular { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TopGelisSekilleri> TopGelisSekilleri { get; set; }
        public virtual DbSet<TopKonumlari> TopKonumlari { get; set; }
        public virtual DbSet<VurusBicimleri> VurusBicimleri { get; set; }
        public virtual DbSet<View_Antrenmanlar> View_Antrenmanlar { get; set; }
        public virtual DbSet<View_AntrenmanlarCMB> View_AntrenmanlarCMB { get; set; }
        public virtual DbSet<View_Antrenorler> View_Antrenorler { get; set; }
        public virtual DbSet<View_VurusBicimleri> View_VurusBicimleri { get; set; }
        public virtual DbSet<PortAyari> PortAyari { get; set; }
        public virtual DbSet<AntrenmanBolge> AntrenmanBolge { get; set; }
    }
}
