//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntrenmanTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sporcular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sporcular()
        {
            this.Antrenmanlar = new HashSet<Antrenmanlar>();
            this.KullaniciSporcular = new HashSet<KullaniciSporcular>();
        }
    
        public int Id { get; set; }
        public int MevkiId { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public int Yas { get; set; }
        public int Kilo { get; set; }
        public int Boy { get; set; }
        public Nullable<int> Ulke { get; set; }
        public Nullable<int> ResimId { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Antrenmanlar> Antrenmanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciSporcular> KullaniciSporcular { get; set; }
        public virtual Mevkiler Mevkiler { get; set; }
        public virtual Resimler Resimler { get; set; }
        public virtual ulkeler ulkeler { get; set; }
    }
}
