//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntrenmanTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopKonumlari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TopKonumlari()
        {
            this.AntrenmanTurleri = new HashSet<AntrenmanTurleri>();
            this.KaleciAntrenmanTurleri = new HashSet<KaleciAntrenmanTurleri>();
            this.KayitSablonu = new HashSet<KayitSablonu>();
        }
    
        public int Id { get; set; }
        public string Adi { get; set; }
        public string EAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AntrenmanTurleri> AntrenmanTurleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KaleciAntrenmanTurleri> KaleciAntrenmanTurleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KayitSablonu> KayitSablonu { get; set; }
    }
}
