//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntrenmanTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_AntrenmanlarCMB
    {
        public int AntrenmanId { get; set; }
        public string AntrenmanTurleri { get; set; }
        public string EAntrenmanTurleri { get; set; }
        public int SporcuId { get; set; }
        public int TopKonumId { get; set; }
    }
}
