//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntrenmanTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_HaftalikBasariliAtis
    {
        public string AdSoyad { get; set; }
        public string AntrenmanTurleri { get; set; }
        public Nullable<int> BirHaftaBasariliAtisSayisi { get; set; }
        public Nullable<int> IkiHaftaBasariliAtisSayisi { get; set; }
        public Nullable<int> UcHaftaBasariliAtisSayisi { get; set; }
        public Nullable<int> DortHaftaBasariliAtisSayisi { get; set; }
        public Nullable<int> BesHaftaBasariliAtisSayisi { get; set; }
        public int Id { get; set; }
        public Nullable<int> AntrenamTuruId { get; set; }
    }
}
