//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntrenmanTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_AylikAtis
    {
        public string AdSoyad { get; set; }
        public string AntrenmanTurleri { get; set; }
        public Nullable<int> Yil { get; set; }
        public Nullable<int> AntrenamTuruId { get; set; }
        public int Id { get; set; }
        public Nullable<int> OcakAtisSayisi { get; set; }
        public Nullable<int> SubatAtisSayisi { get; set; }
        public Nullable<int> MartAtisSayisi { get; set; }
        public Nullable<int> NisanAtisSayisi { get; set; }
        public Nullable<int> MayisAtisSayisi { get; set; }
        public Nullable<int> HaziranAtisSayisi { get; set; }
        public Nullable<int> TemmuzAtisSayisi { get; set; }
        public Nullable<int> AgustosAtisSayisi { get; set; }
        public Nullable<int> EylulAtisSayisi { get; set; }
        public Nullable<int> EkimAtisSayisi { get; set; }
        public Nullable<int> KasimAtisSayisi { get; set; }
        public Nullable<int> AralikAtisSayisi { get; set; }
    }
}
