//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntrenmanTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_HaftalikAtis
    {
        public string AdSoyad { get; set; }
        public string AntrenmanTurleri { get; set; }
        public int Id { get; set; }
        public Nullable<int> AntrenamTuruId { get; set; }
        public Nullable<int> Ay { get; set; }
        public Nullable<int> Yil { get; set; }
        public Nullable<int> BirHaftaAtisSayisi { get; set; }
        public Nullable<int> IkiHaftaAtisSayisi { get; set; }
        public Nullable<int> UcHaftaAtisSayisi { get; set; }
        public Nullable<int> DortHaftaAtisSayisi { get; set; }
        public Nullable<int> BesHaftaAtisSayisi { get; set; }
    }
}
