//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntrenmanTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_AylikBasariliAtis
    {
        public string AdSoyad { get; set; }
        public string AntrenmanTurleri { get; set; }
        public Nullable<int> OcakBasariliAtisSayisi { get; set; }
        public Nullable<int> SubatBasariliAtisSayisi { get; set; }
        public Nullable<int> MartBasariliAtisSayisi { get; set; }
        public Nullable<int> NisanBasariliAtisSayisi { get; set; }
        public Nullable<int> MayisBasariliAtisSayisi { get; set; }
        public Nullable<int> HaziranBasariliAtisSayisi { get; set; }
        public Nullable<int> TemmuzBasariliAtisSayisi { get; set; }
        public Nullable<int> AgustosBasariliAtisSayisi { get; set; }
        public Nullable<int> EylulBasariliAtisSayisi { get; set; }
        public Nullable<int> EkimBasariliAtisSayisi { get; set; }
        public Nullable<int> KasimBasariliAtisSayisi { get; set; }
        public Nullable<int> AralikBasariliAtisSayisi { get; set; }
        public int Id { get; set; }
        public Nullable<int> AntrenamTuruId { get; set; }
    }
}
