//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntrenmanTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class VurusBicimleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VurusBicimleri()
        {
            this.AntrenmanTurleri = new HashSet<AntrenmanTurleri>();
        }
    
        public int Id { get; set; }
        public string Adi { get; set; }
        public Nullable<int> ResimId { get; set; }
        public string EAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AntrenmanTurleri> AntrenmanTurleri { get; set; }
        public virtual Resimler Resimler { get; set; }
    }
}
